### ISSUE TITLE
StackOverflow error on filter method

### ISSUE THREAD

**Issue by ajnavarro** [bblfsh/client-scala#18] opened 2017-10-12 08:44 UTC
In some cases, a StackOverflowError happens on bblfsh.filter method:

Exception in thread "Executor task launch worker for task 2273" java.lang.StackOverflowError
        at org.bblfsh.client.libuast.Libuast.filter(Native Method)
        at org.bblfsh.client.BblfshClient.filter(BblfshClient.scala:34)
        at tech.sourced.api.udf.QueryXPathUDF$$anonfun$queryXPath$2.apply(QueryXPathUDF.scala:46)
        at tech.sourced.api.udf.QueryXPathUDF$$anonfun$queryXPath$2.apply(QueryXPathUDF.scala:44)
        at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
        at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
        at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
        at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
        at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:241)
        at scala.collection.AbstractTraversable.flatMap(Traversable.scala:104)
        at tech.sourced.api.udf.QueryXPathUDF$.queryXPath(QueryXPathUDF.scala:44)
        at tech.sourced.api.udf.QueryXPathUDF$$anonfun$apply$1.apply(QueryXPathUDF.scala:25)
        at tech.sourced.api.udf.QueryXPathUDF$$anonfun$apply$1.apply(QueryXPathUDF.scala:24)
        at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIterator.processNext(Unknown Source)
        at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
        at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$8$$anon$1.hasNext(WholeStageCodegenExec.scala:395)
        at org.apache.spark.sql.execution.SparkPlan$$anonfun$2.apply(SparkPlan.scala:234)
        at org.apache.spark.sql.execution.SparkPlan$$anonfun$2.apply(SparkPlan.scala:228)
        at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsInternal$1$$anonfun$apply$25.apply(RDD.scala:827)
        at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsInternal$1$$anonfun$apply$25.apply(RDD.scala:827)
        at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
        at org.apache.spark.scheduler.Task.run(Task.scala:108)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:335)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

**Comment by abeaumont** [comment] 2017-10-13 09:00
Can you provide some additional insight? Which query causes the problem, how to reproduce it, etc.?

**Comment by abeaumont** [comment] 2017-10-13 11:32
I've made some stress tests and I cannot reproduce this.

**Comment by juanjux** [comment] 2017-10-16 08:25
@ajnavarro if you're parsing complex files probably is using more stack than configured (typically 512KB or 1MB), could you try to increase it with `-Xss8M`?

**Comment by erizocosmico** [comment] 2017-10-16 11:34
If I'm not mistaken, we've got this error with the tests, which is a 1 line python script:

```python
with open('somefile.txt') as f: contents=f.read()
```

**Comment by juanjux** [comment] 2017-10-16 16:00
After a nice debugging session, I'm almost sure that this and #19 were caused because I wasn't locking the access to filter() with a mutex. 

Based on my tracing of the problem, this almost surely caused the random errors we've been seeing with the "NoClassDefFound" randomly on random unittests, which in turn caused a [lot of recursive calls](https://gist.github.com/juanjux/da973d824bee5c0ba4abf8f765f12dac) if you have a big enough stack, or a StackOverflow if don't.

PR #23 should fix this when merged.

**Closed** 2017-10-16 16:06 UTC
